Add style checks
graphql-dotnet/graphql-dotnet pull request #2819
Opened 2021-12-27 18:49 UTC by sungam3r

2021-12-27 20:40 UTC, sungam3r commented
~60-70 warnings fixed

2021-12-28 01:26 UTC, Shane32 requested changes

2021-12-28 01:26 UTC, Shane32 commented on src/GraphQL.DataLoader/DataLoaderDocumentListener.cs
> +        public Task BeforeExecutionAwaitedAsync(IExecutionContext _)
Public api should not have argument names called `_`

2021-12-28 01:26 UTC, Shane32 commented on src/GraphQL.ApiTests/GraphQL.DataLoader.approved.txt
> +        public System.Threading.Tasks.Task BeforeExecutionStepAwaitedAsync(GraphQL.Execution.IExecutionContext _) { }
Public api should not have arguments named `_`

2021-12-28 01:26 UTC, Shane32 commented on src/GraphQL/Utilities/SchemaBuilder.cs
> +            return type!;
Seems like either it should be nullable return value or else use the Item property so an exception is thrown if the key doesn’t exist. Probably do the former and then change to the latter in a separate PR

2021-12-28 18:52 UTC, Shane32 commented on src/GraphQL.ApiTests/GraphQL.DataLoader.approved.txt
> +        public System.Threading.Tasks.Task BeforeExecutionStepAwaitedAsync(GraphQL.Execution.IExecutionContext _) { }
We should check why this method BeforeExecutionStepAwaitedAsync exists in the develop branch - I thought it was removed when the obsolete members was removed. Maybe I missed it.

2021-12-28 19:20 UTC, sungam3r commented
Done

2021-12-28 19:53 UTC, Shane32 approved these changes

2021-12-28 20:21 UTC, merged